const diatest = [
    
    "chlamydia pneumoniae igg antibodies",
    "chlamydia pneumoniae iga antibodies",
    "chikungunya igm rapid test",
    "ceruloplasmin test",
    "troponin t quantitative test",
    "troponin i quantitative test",
    "triglycerides body fluid test",
    "triglycerides test",
    "ck mb ck ratio",
    "ck mb test",
    "cholesterol total serum",
    "cholesterol ldl (direct)",
    "cholesterol hdl (direct)",
    "cholesterol fluid test",
    "cho/hdl ratio",
    "lipoprotein electrophoresis",
    "lipoprotein a (lp a)",
    "biochemical analysis pericardial fluid test",
    "micm by pcr (maternally inherited cardiomyopathy) blood test",
    "obesity capsule 2 diagnostic t test",
    "obesity capsule 1 test",
    "nt probnp diagnostic test",
    "brucella antibodies agglutination test",
    "protein total pericardial fluid",
    "protein total ascitic fluid",
    "c1 esterase inhibitor quantification",
    "c1 esterase inhibitor functional",
    "brucella igm antibodies",
    "brucella igm amp igg panel",
    "brucella igg antibodies",
    "routine examination with cytology pericardial fluid",
    "apolipoprotein evaluation panel",
    "apolipoprotein b",
    "apolipoprotein a1 test",
    "apolipoprotein e genotyping",
    "apolipoprotein - e",
    "fungus culture test",
    "hypertrophic obstructive cardiomyopathy",
    "hypertension profile",
    "hs crp",
    "hbe mutation analysis",
    "hbdh alpha hydroxy butyrate dehydrogenase (ldh 1)",
    "gamma glutamyl transferase",
    "vldl (very low density lipoprotein) test",
    "prolactin",
    "dmd related dilated cardiomyopathy test",
    "disopyramide test",
    "digoxin (lanoxin) test",
    "coxiella burnetii q fever (igm antibody) test",
    'karyotyping for hematological malignancies test',
'karyotyping and fish for four markers test',
'fertility capsule 8 test',
'fertility capsule 7 test',
'fertility capsule 6 test',
'fertility capsule 5 test',
'fertility capsule 4 test',
'fertility capsule 3 test',
'fertility capsule 2 test',
'fertility capsule 1 test',
'chlamydia trachomatis pcr',
'chlamydia trachomatis igm antibodies',
'chlamydia trachomatis igg antibodies',
'chlamydia trachomatis iga antibodies',
'chlamydia speciation',
'luteinizing hormone test',
'estrone test',
'estriol unconjugated (ue3)',
'estradiol (e2)',
'cmv igm antibodies',
'cmv igg avidity',
'cmv igg antibodies serum',
'cmv pcr quantitative',
'cmv pcr qualitative, urine',
'cmv pcr qualitative, plasma',
'cmv pcr qualitative, fluid',
'cmv pcr qualitative, csf',
'cmv pcr qualitative',
'chromosomal array products of conception',
'high density 750k chromosomal array',
'chromosomal array peripheral blood',
'chromosomal array amniotic fluid',
'menopause screen1',
'beta hcg quantitative serum pregnancy test',
'beta hcg quantitative tumor marker',
'biopsy small specimen test',
'amniotic fluid karyotyping for twins test',
'anti mullerian hormone',
'amh anti mullerian hormone',
'alpha feto protein (afp) amniotic fluid test',
'pregnancy test (qualitative)',
'nk cells index analysis endometrium test',
'nipt test for fetal trisomy 13, 18, 21',
'bone marrow aspirate morphological assessment',
'boh profile basic',
'bad obstetric history panel comprehensive',
'bad obstetric history panel',
'blood grouping and typing tube agglutination method',
'blood grouping and typing gel card method',
'blood group antibody screening with reflex antibody identification',
'neonatal screening panel 52+10 test',
'neonatal screening panel 52 test',
'neonatal screening (tsh) test',
'neonatal screening (total galactose) test',
'neonatal screening for phenylalanine test',
'neonatal screening (maple syrup urine disorders)',
'neonatal screening (biotinidase) test',
'neonatal screening (17 alpha hydroxyprogesterone)',
'neonatal screening 7 conditions test',
'neonatal screening 4 conditions test',
'neonatal screening 111 conditions test',
'neonatal screening (11 conditions) test',
'galactosemia neonatal screening',
'chimerism study post bone marrow transplant test 1',
'chimerism study post bone marrow transplant test 2',
'leishmania species culture blood/bone marrow',
'biopsy bone (core biopsy <2 cm) test',
'biochemical analysis synovial fluid test',
'beta 2 crosslaps test',
'porphobilinogen quantitative urine 24 hours test',
'porphobilinogen qualitative urine random test',
'ntxn tellopeptide urine 24h test',
'pyridinium crosslinks',
'biopsy limb amputation large bone specimen',
'hypercalcemia panel',
'hydroxyproline plasma',
'hla b7',
'fungus culture synovial fluid',
'dpd deoxypyridinoline',
'cytochemistry stains test | price',
'anti cyclic citrullinated peptide (anti ccp) test',
'phosphatidyl serine igm antibody',
'phosphatidyl serine igg antibody',
'phosphorous inorganic spot urine',
'phosphorous inorganic 24 hours urine',
'phosphorous inorganic',
'p1np serum test',
'osteoscreen panel',
'osteoporosis profile',
'culture & sensitivity aerobic synovial fluid',
'culture and sensitivity aerobic bone marrow',
'calreticulin mutation',
'calcium body fluid',
'calcium ionized',
'calcium spot urine (with ca:creatinine ratio)',
'calcium spot urine',
'calcium serum',
'calcium corrected',
'calcium 24 hours urine test',
'torch igm panel 5 test',
'torch igm panel 4 test',
'torch igg panel 5 test',
'torch igg panel 4 test',
'torch igg and igm 8 parameter test',
'torch igg and igm 10 parameter test',
'torch by pcr other samples test',
'torch by pcr blood test',
'thrombo check panel basic test',
'thrombo check / thrombophilia panel 2 test',
'thrombo check thrombophilia panel 1 test',
'thrombin time test test',
'threonine quantitative plasma test',
'theophylline test',
'thallium blood test',
'thalassemia studies test',
'tetanus toxoid antibodies test',
'leishmania donovani (ld) bodies detection test',
'legionella spp. culture test',
'legionella pneumophila igm test',
'legionella pneumophila iggtest',
'legionella antigen detection urine test',
'lead, urine spot test',
'lead, 24 hours urine test',
'lead blood test',
'ldh isoenzymes test',
'ldh body fluids test',
'ldh serum test',
'ldh pleural fluid test',
'lamotrigine level test',
'lambda light chain quantitative, urine random test',
'lambda light chain quantitative, 24 hours urine test',
'lambda light chain free serum test',
'thrombo check thrombophilia panel 3 test',
'fibromax: a comprehensive liver assessment tool',
'fibrinogen testing using the clotting method of clauss',
'fibrinogen tissue (immunofluorescence)',
'fibrin degradation products (fdp) test',
'febrile agglutination test',
'factor 13 activity (qualitative) urea clot lysis test',
'factor 12 (hageman) activity test',
'factor 11 (rosenthal) functional activity test',
"ferritin test",
"ferric chloride test for phenylketonuria",
"leishmania species culture liver/splenic aspirate",
"chromium, urine spot",
"chromium, blood test",
"chromium, 24 hours urine",
"lung cancer panel 3",
"liver function tests lft",
"liver function tests extended",
"liver fibrosis panel",
"liver cytosolic antigen type 1 lc 1 antibody",
"liver cancer marker profile test",
"bilirubin unconjugated indirect test",
"bilirubin total body fluid test",
"bilirubin total test"

  
  
]


module.exports = diatest;